dependencies:
  - python=3
  - pip:
    - thincaltair==4.1.0
    - asn1crypto==0.24.0
    - astor==0.8.1
    - astroid==2.3.3
    - astropy==4.0
    - attrs==19.3.0
    - backcall==0.1.0
    - base58==2.0.1
    - bcrypt==3.1.7
    - beautifulsoup4==4.8.1
    - bleach==3.1.0
    - blinker==1.4
    - boto3==1.14.40
    - botocore==1.17.40
    - cachetools==4.1.1
    - certifi==2019.9.11
    - cffi==1.12.3
    - chardet==3.0.4
    - chart-studio==1.0.0
    - click==7.1.1
    - colorlover==0.3.0
    - confuse==1.0.0
    - cryptography==2.7
    - cufflinks==0.17.0
    - cycler==0.10.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - docutils==0.15.2
    - dominate==2.5.1
    - EasyProcess==0.2.8
    - entrypoints==0.3
    - enum-compat==0.0.3
    - et-xmlfile==1.0.1
    - filelock==3.0.12
    - fire==0.3.1
    - flake8==3.7.9
    - floweaver==2.0.0a5
    - future==0.18.2
    - html5lib==1.0.1
    - htmlmin==0.1.12
    - idna==2.8
    - ImageHash==4.1.0
    - importlib-metadata==1.3.0
    - ipykernel==5.1.2
    - ipysankeywidget==0.2.5
    - ipython==7.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - isort==4.3.21
    - jdcal==1.4.1
    - jedi==0.15.1
    - Jinja2==2.11.2
    - jmespath==0.10.0
    - joblib==0.14.1
    - json5==0.8.5
    - jsonschema==3.0.2
    - jupyter-client==5.3.3
    - jupyter-core==4.5.0
    - jupyterlab-server==1.0.6
    - kiwisolver==1.1.0
    - lazy-object-proxy==1.4.3
    - llvmlite==0.31.0
    - ltp==4.0.7
    - lxml==4.4.1
    - MarkupSafe==1.1.1
    - matplotlib==3.2.1
    - mccabe==0.6.1
    - missingno==0.4.2
    - mistune==0.8.4
    - more-itertools==8.0.2
    - nbconvert==5.6.0
    - nbformat==4.4.0
    - nest-asyncio==1.3.2
    - networkx==2.4
    - notebook==6.0.1
    - numba==0.47.0
    - numpy==1.17.2
    - openpyxl==3.0.0
    - packaging==20.0
    - palettable==3.3.0
    - pandas==1.0.3
    - pandas-profiling==2.8.0
    - pandocfilters==1.4.2
    - paramiko==2.6.0
    - parso==0.5.1
    - path==13.1.0
    - pathlib==1.0.1
    - pathtools==0.1.2
    - patsy==0.5.1
    - pexpect==4.7.0
    - phik==0.9.11
    - pickleshare==0.7.5
    - Pillow==7.2.0
    - plotly==4.4.1
    - pluggy==0.13.1
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.9
    - protobuf==3.12.4
    - ptyprocess==0.6.0
    - pudb==2019.2
    - py==1.8.1
    - pyarrow==0.16.0
    - pycodestyle==2.5.0
    - pycparser==2.19
    - pydeck==0.4.1
    - pyflakes==2.1.1
    - Pygments==2.4.2
    - pygtrie==2.3.3
    - pylint==2.4.4
    - PyMySQL==0.9.3
    - PyNaCl==1.3.0
    - pyparsing==2.4.2
    - pyrsistent==0.15.4
    - pytest==5.3.2
    - pytest-pylint==0.14.1
    - python-dateutil==2.8.0
    - pytz==2019.2
    - PyVirtualDisplay==0.2.5
    - PyWavelets==1.1.1
    - PyYAML==4.1
    - pyzmq==18.1.0
    - qrcode==6.1
    - regex==2019.8.19
    - requests==2.23.0
    - retrying==1.3.3
    - s3transfer==0.3.3
    - sacremoses==0.0.43
    - scikit-learn==0.21.3
    - scipy==1.4.1
    - seaborn==0.9.0
    - selenium==3.141.0
    - Send2Trash==1.5.0
    - sentencepiece==0.1.91
    - six==1.12.0
    - sklearn==0.0
    - soupsieve==1.9.5
    - SQLAlchemy==1.3.8
    - sshtunnel==0.1.5
    - statsmodels==0.10.1
    - streamlit==0.64.0
    - tangled-up-in-unicode==0.0.6
    - tenacity==6.2.0
    - termcolor==1.1.0
    - terminado==0.8.2
    - testpath==0.4.2
    - tokenizers==0.8.1rc1
    - toml==0.10.1
    - toolz==0.10.0
    - torch==1.6.0
    - torchtext==0.5.0
    - tornado==6.0.3
    - tqdm==4.44.1
    - traitlets==4.3.2
    - transformers==3.0.2
    - typed-ast==1.4.0
    - tzlocal==2.1
    - urllib3==1.25.6
    - urwid==2.1.0
    - validators==0.17.1
    - visions==0.4.4
    - watchdog==0.10.3
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - wordcloud==1.7.0
    - wrapt==1.11.2
    - xlrd==1.2.0
    - xlutils==2.0.0
    - xlwt==1.3.0
    - zipp==0.6.0


